version: '3.8'

services:
  # ==================== PostgreSQL ====================
  customer-db:
    image: postgres
    container_name: customer-db
    environment:
      POSTGRES_DB: customer-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - customer_db_data:/var/lib/postgresql/data

  account-db:
    image: postgres
    container_name: account-db
    environment:
      POSTGRES_DB: account-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - account_db_data:/var/lib/postgresql/data

  notification-db:
    image: postgres
    container_name: notification-db
    environment:
      POSTGRES_DB: notification-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - notification_db_data:/var/lib/postgresql/data

  user-db:
    image: postgres
    container_name: user-db
    environment:
      POSTGRES_DB: user-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - user_db_data:/var/lib/postgresql/data

  keycloak-db:
    image: postgres
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  # ==================== Kafka / Zookeeper ====================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  # ==================== Keycloak ====================
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    container_name: keycloak
    command: start-dev --http-port=9090
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "9090:9090"
    depends_on:
      - keycloak-db

  # ==================== Spring Boot Microservices ====================
  bank-discovery-service:
    image: fouadsaididev/bank-discovery-service:v1.0.0
    container_name: bank-discovery-service
    ports:
      - "8761:8761"

  bank-customer-service:
    image: fouadsaididev/bank-customer-service:v1.0.0
    container_name: bank-customer-service
    ports:
      - "8081:8081"
    environment:
      DB_URL: jdbc:postgresql://customer-db:5432/customer-db
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/bank-app
      KEYCLOAK_JWK_URI: http://keycloak:9090/realms/bank-app/protocol/openid-connect/certs
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - customer-db
      - bank-discovery-service
      - keycloak

  bank-account-service:
    image: fouadsaididev/bank-account-service:v1.0.0
    container_name: bank-account-service
    ports:
      - "8082:8082"
    environment:
      DB_URL: jdbc:postgresql://account-db:5432/account-db
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/bank-app
      KEYCLOAK_JWK_URI: http://keycloak:9090/realms/bank-app/protocol/openid-connect/certs
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - account-db
      - bank-discovery-service
      - bank-customer-service
      - keycloak

  bank-notification-service:
    image: fouadsaididev/bank-notification-service:v1.0.0
    container_name: bank-notification-service
    ports:
      - "8083:8083"
    environment:
      DB_URL: jdbc:postgresql://notification-db:5432/notification-db
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/bank-app
      KEYCLOAK_JWK_URI: http://keycloak:9090/realms/bank-app/protocol/openid-connect/certs
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
      - notification-db
      - bank-discovery-service
      - keycloak

  user-management-service:
    image: fouadsaididev/user-management-service:v1.0.0
    container_name: user-management-service
    ports:
      - "8088:8088"
    environment:
      DB_URL: jdbc:postgresql://user-db:5432/user-db
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/bank-app
      KEYCLOAK_JWK_URI: http://keycloak:9090/realms/bank-app/protocol/openid-connect/certs
    depends_on:
      - user-db
      - bank-discovery-service
      - keycloak

  report-service:
    image: fouadsaididev/report-service:v1.0.0
    container_name: report-service
    ports:
      - "8084:8084"
    environment:
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
      KEYCLOAK_ISSUER_URI: http://keycloak:9090/realms/bank-app
      KEYCLOAK_JWK_URI: http://keycloak:9090/realms/bank-app/protocol/openid-connect/certs
    depends_on:
      - bank-discovery-service
      - keycloak

  bank-gateway-service:
    image: fouadsaididev/bank-gateway-service:v1.0.0
    container_name: bank-gateway-service
    ports:
      - "8888:8888"
    environment:
      DISCOVERY_SERVICE_URL: http://bank-discovery-service:8761/eureka
    depends_on:
      - bank-discovery-service

  bank-angular:
    image: fouadsaididev/bank-angular:v1.0.0
    container_name: bank-angular
    ports:
      - "8086:80"
    depends_on:
      - bank-gateway-service

# ==================== Volumes ====================
volumes:
  customer_db_data:
  account_db_data:
  notification_db_data:
  keycloak_db_data:
  user_db_data:
